#84 Filtering now applies to ExtensibleElement
eclipse/capella-filtering pull request #85
Opened 2023-03-01 12:38 UTC by etraisnel2

Filtering capabilities now apply to ExtensibleElement instead of CapellaElement

This ensures that export works on models with REC/RPL data

Change-Id: I993ddbbc1ab6019b9134474962bf821f4e10464f

2023-03-01 13:45 UTC, pdulth commented on plugins/org.polarsys.capella.filtering.validation/plugin.xml
> +               namespaceUri="http://www.polarsys.org/org.polarsys.kitalpha.emde.model/fa/6.0.0">
this one is weird

2023-03-01 13:45 UTC, pdulth requested changes

2023-03-01 13:45 UTC, pdulth commented on plugins/org.polarsys.capella.filtering.validation/plugin.xml
> +               namespaceUri="http://www.polarsys.org/org.polarsys.kitalpha.emde.model/fa/6.0.0">
this one is weird

2023-03-01 13:52 UTC, etraisnel2 commented on plugins/org.polarsys.capella.filtering.validation/plugin.xml
> +               namespaceUri="http://www.polarsys.org/org.polarsys.kitalpha.emde.model/fa/6.0.0">
Looks like a typo indeed, fixed

2023-03-13 15:10 UTC, pdulth approved these changes

2023-03-13 15:10 UTC, merged